//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 01:30:17 AM CEST 
//


package com.m1big1.businesslayer.server.dto.access;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}DTO">
 *       &lt;sequence>
 *         &lt;element name="root-node" type="{}NodeStructureDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="user-database-id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="search-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rootNode"
})
@XmlRootElement(name = "SearchWordDTO")
public class SearchWordDTO
    extends DTO
{

    @XmlElement(name = "root-node")
    protected NodeStructureDTO rootNode;
    @XmlAttribute(name = "user-database-id", required = true)
    protected int userDatabaseId;
    @XmlAttribute(name = "search-name")
    protected String searchName;

    /**
     * Gets the value of the rootNode property.
     * 
     * @return
     *     possible object is
     *     {@link NodeStructureDTO }
     *     
     */
    public NodeStructureDTO getRootNode() {
        return rootNode;
    }

    /**
     * Sets the value of the rootNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeStructureDTO }
     *     
     */
    public void setRootNode(NodeStructureDTO value) {
        this.rootNode = value;
    }

    /**
     * Gets the value of the userDatabaseId property.
     * 
     */
    public int getUserDatabaseId() {
        return userDatabaseId;
    }

    /**
     * Sets the value of the userDatabaseId property.
     * 
     */
    public void setUserDatabaseId(int value) {
        this.userDatabaseId = value;
    }

    /**
     * Gets the value of the searchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchName() {
        return searchName;
    }

    /**
     * Sets the value of the searchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchName(String value) {
        this.searchName = value;
    }

}
