//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 03:05:24 PM CEST 
//


package com.m1big1.presentationlayer.client.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}DTO">
 *       &lt;sequence>
 *         &lt;element name="root-history-event" type="{}HistoryEventDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rootHistoryEvent"
})
@XmlRootElement(name = "HistoryDTO")
public class HistoryDTO
    extends DTO
{

    @XmlElement(name = "root-history-event")
    protected HistoryEventDTO rootHistoryEvent;

    /**
     * Gets the value of the rootHistoryEvent property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryEventDTO }
     *     
     */
    public HistoryEventDTO getRootHistoryEvent() {
        return rootHistoryEvent;
    }

    /**
     * Sets the value of the rootHistoryEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryEventDTO }
     *     
     */
    public void setRootHistoryEvent(HistoryEventDTO value) {
        this.rootHistoryEvent = value;
    }

}
